### ISSUE TITLE
KeyError on clicking "download" button

### ISSUE THREAD

**Issue by Fak3** [makehumancommunity/community-plugins-assetdownload#12]
NOTE: I can't easily reproduce it when tried again, will add more details if i'll see it again
Running git master makehuman and this plugin. 

I went to download eybrows asset (there is only single one available), clicked "download" on the right. The error appeared in the status bar and nothing happened. Tried few times with same results (KeyError). But after i switched asset type on the left filter menu and them back - the bug is gone...
 Log:
```
Exception during event onClicked
Traceback (most recent call last):
  File "./core/events3d.py", line 211, in callEvent
    method(event)
  File "/home/u1/Documents/makehuman/v1py3/plugins/8_asset_downloader/assetdownload.py", line 274, in onClicked
    self._onBtnDownloadClick()
  File "/home/u1/Documents/makehuman/v1py3/plugins/8_asset_downloader/assetdownload.py", line 328, in _onBtnDownloadClick
    remoteAsset = self.assetdb.remoteAssets[assetType][assetId]
KeyError: 326

**Comment by joepal1976** [comment]
I have yet to reproduce this, but keeping open for now.

**Comment by Aranuvir** [comment]
There hasn't been an update for >6 month. Closing...
