### ISSUE TITLE
not sure if im doing something wrong but i get an issue

### ISSUE THREAD

**Issue by Presentdaygames** [makehumancommunity/community-plugins-assetdownload#22]
Could not load 8_asset_downloader
Traceback (most recent call last):
  File "core\mhmain.py", line 541, in loadPlugin
  File "plugins/8_asset_downloader\__init__.py", line 38, in load
    downloadView = category.addTask(AssetDownloadTaskView(category))
  File "plugins/8_asset_downloader\assetdownload.py", line 76, in __init__
    self._setupTable()
  File "plugins/8_asset_downloader\assetdownload.py", line 398, in _setupTable
    self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
NameError: global name 'QtWidgets' is not defined

**Comment by Aranuvir** [comment]
That's the downside of breaking up plug-in and core development development...

**Comment by joepal1976** [comment]
What version of MH are you trying to combine with which version of the asset downloader plugin?

**Comment by joepal1976** [comment]
Should be working in master now
