### ISSUE TITLE
Cannot get Asset Downloader to Load

### ISSUE THREAD

**Issue by demib72** [makehumancommunity/community-plugins-assetdownload#37]
OS: Pop_OS 22.04

Error Log:

Loading plugin 8_asset_downloader
Could not load 8_asset_downloader
Traceback (most recent call last):
  File "/home/mharris89/Programs/makehuman/makehuman/./core/mhmain.py", line 585, in loadPlugin
    module.load(self)
  File "/home/mharris89/Programs/makehuman/makehuman/plugins/8_asset_downloader/__init__.py", line 38, in load
    downloadView = category.addTask(AssetDownloadTaskView(category))
  File "/home/mharris89/Programs/makehuman/makehuman/plugins/8_asset_downloader/assetdownload.py", line 72, in __init__
    self.assetdb = AssetDB(self)
  File "/home/mharris89/Programs/makehuman/makehuman/plugins/8_asset_downloader/assetdb.py", line 67, in __init__
    self._loadRemoteDB()
  File "/home/mharris89/Programs/makehuman/makehuman/plugins/8_asset_downloader/assetdb.py", line 92, in _loadRemoteDB
    self.remoteJson = json.load(f)
  File "/home/mharris89/anaconda3/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/mharris89/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/mharris89/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/mharris89/anaconda3/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 4206 column 1 (char 263275)

Hello, I installed MakeHuman 1.2.1 and call the program from source (from the makehuman.py file) since I am using the latest version of Ubuntu/Pop_Os. I downloaded the plugins from inside of the program and even tried downloading directly from here. Same error.

**Comment by joepal1976** [comment]
In your ~/documents/makehuman/v1py3/data/community-assets directory, there should be two json files. Can you attach them here? They might need to be zipped if github thinks they are too large.
